django/blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path( 'admin/' , admin.site.urls ),
    url( 'blogApp/' , include( 'blogApp.urls' , namespace = 'blogApp') ) , 
]

django/blog/blogApp/urls.py
from django.conf.urls import url
from . import views
 

app_name = 'blogApp'
urlpatterns = [
	url( r'^$' , views.post_list , name = 'post_list') ,
	url( r'^(?P<id>[0-9]+)/$' , views.post_detail , name = 'post_detail'),
	url( r'^(?P<id>[0-9]+)/share/$' , views.post_share , name = 'post_share'),

]

django/blog/blogApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):

	def get_queryset(self):
		return super( PublishedManager , self ).get_queryset().filter(status = 'published')


class Post(models.Model):
	STATUS_CHOICES = {
	('draft' , 'Draft'),
	('published' , 'Published')
	}
	title = models.CharField( max_length = 250 )
	slug = models.SlugField( max_length = 250 , unique_for_date = 'publish')
	author = models.ForeignKey( User , related_name = 'blog_posts' , on_delete = 'CASCADE')
	body = models.TextField()
	publish = models.DateTimeField( default = timezone.now )
	created = models.DateTimeField( auto_now_add = True )
	updated = models.DateTimeField( auto_now = True )
	status = models.CharField( max_length = 10 , choices = STATUS_CHOICES , default = 'draft' )

	published = PublishedManager()
	objects = models.Manager()


	class Meta:
		ordering = ( '-publish' , )

	def __str__(self):
		return self.title

'''
	def get_absolute_url(self):
		return reverse( 'blogApp:post_detail' , args = [ self.publish.year , self.publish.strftime("%m") ,
			self.publish.strftime("%d") , self.slug])

'''

class Comment(models.Model):
	post = models.ForeignKey( Post , related_name = 'comments' , on_delete = 'CASCADE')
	name = models.CharField( max_length = 80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField( auto_now_add = True )
	updated = models.DateTimeField( auto_now = True )
	active = models.BooleanField( default = True)

	class Meta:
		ordering = ( 'created',)

	def __str__(self):
		return 'Comment by {} on {}'.format( self.name , self.post )

django/blog/blogApp/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField( max_length = 25 )
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField( required = False , widget = forms.Textarea )

class CommentForm(forms.ModelForm):
    class Meta:
    	model = Comment
    	fields = ('name' , 'email' , 'body' )
    	

django/blog/blogApp/views.py
from django.shortcuts import render , get_object_or_404
from .models import Post , Comment
from django.core.paginator import Paginator, EmptyPage , PageNotAnInteger
from .forms import EmailPostForm , CommentForm
from django.core.mail import send_mail


# Create your views here.

def post_list(request):
	posts_list=Post.published.all()
	paginator = Paginator(posts_list , 5)



	print ( "\n\n\n\n" )
	print ( "We have a request" )
	print ( "Scheme  " + str(request.scheme) )
	print ( "Body  " + str( request.body ) )
	print ( "Path " + str( request.path) )
	print ( "Path_Info " + str( request.path_info ))
	print ( "Method " + str  (request.method) )
	print ( "Get" + str (request.GET ) )
	#for post in posts_list:
	#	print (post.get_absolute_url())
	print ( "\n\n\n\n" )

	try:
		page = request.GET['page']
		posts = paginator.page(page)
	except:
		posts=paginator.page(1)

	return render( request , 'blogApp/post/list.html' , { 'posts' : posts } )



def post_detail( request, id ):
	post = get_object_or_404( Post , pk=id )
	comments = post.comments.filter( active = True )
	dummy_variable = "This is the dummy_variable"

	if request.method == 'POST' :
		comment_form = CommentForm( data = request.POST )
		if comment_form.is_valid():
			new_comment = comment_form.save(commit = False)
			new_comment.post = post
			new_comment.save()
	else:
		comment_form = CommentForm()

	return render( request , 'blogApp/post/detail.html' , { 'post' : post , 'comments' : comments , 'comment_form' : comment_form } )


def post_share( request , id ):
	post = get_object_or_404( Post , pk=id )
	sent = False

	if request.method == 'POST' :
		form = EmailPostForm( request.POST )

		if form.is_valid():
			cd = form.cleaned_data
			subject = "{} ({}) recommends you reading '{}' ".format( cd['name'] , cd['email'] , post.title ) 
			message = post.body + '\n' + '{} comment on this '.format( cd['name'] , cd['comments'])
			send_mail( subject , message , 'panshul.garg@toppr.com' , [cd['to']] )
			sent = True

	else:
		form = EmailPostForm()

	return render(request , 'blogApp/post/share.html' , { 'post' : post , 'form' : form , 'sent_mail' : sent})

django/blog/blogApp/templates/blogApp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title> {% block title %} {% endblock %}</title>
	
	<link href="{% static 'css/blog.css' %}" rel = "stylesheet">


</head>
<body>
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
	<div id = "sidebar">
		<h2> My Blog </h2>
		<p> This is my blog. </p>
	</div>
</body>
</html>

django/blog/blogApp/templates/blogApp/pagination.html
<div class = "pagination">
	<span class = "step-links">
		{% if page.has_previous %}
			<a href = "?page={{ page.previous_page_number }}"> Previous </a>
		{% endif %}
		<span class = "current" >
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href = "?page={{ page.next_page_number }}"> Next </a>

		{% endif %}

	</span>
</div>

django/blog/blogApp/templates/blogApp/post/detail.html
{% extends "blogApp/base.html" %}
{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
{% if dummy_variable %}
<p>we can acesss anything</p>
{% endif %}


<h1>{{ post.title }}</h1>
<p class="date">
	Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body }}
{% with comments.count as total_comments %}
<h2>
	{{ total_comments }} comment {{ total_comments | pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class = "comment">
	<p class="info">
		Comment {{ forloop.counter }} by {{ comment.name }}
		{{ comment.created }}
	</p>
		{{comment.body | linebreaks }}

	</div>
	{% empty %}
	<p> There are no comments yet. </p>
	{% endfor %}

<p>
	<a href = "{% url 'blogApp:post_share' post.pk %}">Share this post</a> <br>

</p>

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2> Add a new comment </h2>
<form action = "" method = "post">
	{{ comment_form.as_p}}
	{% csrf_token %}
	<p><input type="submit" name="add comment"></p>
	</form>
	{% endif %}
	
{% endblock %}

django/blog/blogApp/templates/blogApp/post/list.html
{% extends "blogApp/base.html" %}
{% block title %}
My Blog
{% endblock %}

{% block content %}
<h1> My Blog </h1>
{% for post in posts %}
<h2> <a href = "{% url 'blogApp:post_detail' post.pk %}"> {{ post.title }}</a> </h2>
<p class = "date" >
 This is post number {{post.pk}}<br>
Published {{ post.publish }} by {{ post.author }} </p>
 {{ post.body}}
 {% endfor %}
   {% include "blogApp/pagination.html" with page=posts %}
 {% endblock %}

django/blog/blogApp/templates/blogApp/post/share.html
{% extends 'blogApp/base.html' %}

{% block title %}
Share a Post
{% endblock %}

{% block content %}
{% if sent_mail %}
<h2> Email was sent successfully. </h2>
<p> {{ post.title }} was shared with {{ cd.email }}</p>

{% else %}
<h1> Share "{{ post.title }}" by email </h1>
<form action = "" method = "post">
	{{ form.as_p }}
	{% csrf_token %}
	<input type = "submit" value = "sent-email">
</form>

{% endif %}
{% endblock %}